### ISSUE TITLE
run a scrit in "silent" background mode

### ISSUE THREAD

**Issue by berteh** [aoloe/scribus-script-repository#30]
Hello @aoloe,

I would like to run a script (like https://github.com/aoloe/scribus-script-repository/blob/master/to-pdf/to-pdf.py) in background. Ideally the user would see nothing, just eventually get a warning when execution is completed or an error happened.

Would that be possible ?

The current way of calling ``Scribus.exe -g -py to-pdf.py -- D:\test\t.sla`` does run Scribus in the foreground and freezes my computer as long as the generation is happening.

Thanks.
Berteh, also on behalf of @jvr14115

**Comment by aoloe** [comment]
hoi @berteh , my computer is (mostly) fast enough, that the opening of the file is mostly just a flickering.
but i had an issue some time ago that was keeping busy my processor (or something else) and, then, i started seeing that, indeed scribus just normally opens and closes again.

i know that scribus cannot completely run without a GUI, but i also thought that -g (--no-gui) was suppress most of the GUI.

from my point of view, there seems to be a bug... would you mind reporting it to the official scribus bug tracker?

**Comment by berteh** [comment]
thanks. did so at https://bugs.scribus.net/view.php?id=15255
