### ISSUE TITLE
Spot Color PDF

### ISSUE THREAD

**Issue by koosthoe** [aoloe/scribus-script-repository#34]
I am trying to use Scribus to convert a SVG to PDF and then add a spot color to the PDF. The spot color has to be named "CutContour" for the Vinyl Cutter to know where to cut. Nothing I do seems to create a Spot Color. I think I might be using the wrong type of PDF but am not sure. I think the PDF needs to be PDF/X-3 but the pdf.version only except ints so I dont know what to use.
```py
import scribus

scribus.openDoc('_bnew.svg')

pdf = scribus.PDFfile()

scribus.defineColorCMYKFloat("CutContour", 1, 99, 0, 0)
scribus.setSpotColor("CutContour", 1)

scribus.replaceColor("FromSVG#ec008c", "CutContour")

scribus.deleteColor("FromSVG#ec008c", "CutContour")


pdf.version = 1.3
pdf.file = 'output1.pdf'
pdf.save()
```

**Comment by aoloe** [comment]
this is not a support forum, and i've just replied to your question on stackoverflow...

the solution to your problem is to use:

```py
pdf.outdst = 1
```

to get scribus to export for printing (and avoiding the conversion to rgb)
