### ISSUE TITLE
how to use mail-merge from command line?

### ISSUE THREAD

**Issue by supersexy** [aoloe/scribus-script-repository#37]
how to use mail-merge from command line so that I can automate it?

**Comment by aoloe** [comment]
i see that you have found this too.

i'm currently not active in the scribus world and i won't be able to help you on this.  
... except if you are ready to pay for consulting. or if you can start an healthy project that brings scribus forward.

again, use https://forums.scribus.net if you need help.  
this is for issues...

(small hint: if you have a look at other scripts you will find hints on how you can start the scripts from the command line...)
